### ISSUE TITLE
Feature: upper case route if route is non-numeric

### ISSUE THREAD

**Issue by blakeyoder** [jonthornton/MTAPI#12]
What are your thoughts on having the route be upper cased for all non-numeric routes.

`/by-route/G` and `/by-route/g` would return the same data set. As is, the lower cased route returns an empty list.

**Comment by jonthornton** [comment]
I like that suggestion - returning an empty list is a pretty confusing response. What do you think of canonicalizing on either upper or lower case, and having the other case return 301 redirects to the canonical URL?
