### ISSUE TITLE
503 Error on all API feeds...

### ISSUE THREAD

**Issue by Williepedia** [jonthornton/MTAPI#15]
My API Key works on the feeds listed on the http://datamine.mta.info/list-of-feeds site, however it doesn't seem to work with the feed urls in the mtapi.py file.

Any idea what the difference between these two feeds might be? Out of curiosity, how did you find the api-endpoint.mta.info urls in the first place? I can't seem to find them referenced anywhere.

**Comment by jonthornton** [comment]
The MTA has a new API gateway with its own keys at https://api.mta.info/#/landing. They asked developers to move to these endpoints a couple months ago https://groups.google.com/forum/#!topic/mtadeveloperresources/_6LRqKkTCtw

Thanks for flagging this! I've updated the MTAPI readme to point to the correct MTA site.

**Comment by Williepedia** [comment]
Thank you! And thank you for work on this repo. It is a godsend compared to dealing with the headaches of getting it up and running from the source.
