### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by realswamo** [jonthornton/MTAPI#16]
Hello, when I run the script it is giving me a type error:

Traceback (most recent call last):
  File "app.py", line 62, in <module>
    threaded=app.config['THREADED'])
  File "/home/pi/Desktop/MTAPI-master/mtapi/mtapi.py", line 84, in __init__
    self._stations = json.load(f)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

I deleted the folder and re-did all the installation. Thanks for creating this, it really comes in handy!

**Comment by jonthornton** [comment]
This kinda looks like a problem with `STATIONS_FILE` in the config. What does your `settings.cfg` look like? (Don't share your MTA API key)

**Comment by realswamo** [comment]
Hey there, here is what my settings.cfg looks:

```
MTA_KEY = '***************'
STATIONS_FILE = './data/stations.json'
CROSS_ORIGIN = ''
MAX_TRAINS=10
MAX_MINUTES=30
CACHE_SECONDS=60
THREADED=True
DEBUG = True
```

**Comment by jonthornton** [comment]
Should be fixed in https://github.com/jonthornton/MTAPI/commit/a0b421a929c6d232c711af3a6435de3df1dddf5f
