### ISSUE TITLE
Request some guidance

### ISSUE THREAD

**Issue by fixingthingsguy** [jonthornton/MTAPI#34]
Dear Developers, I've been trying to get things working with MTAPI. I've worked my way through a bunch of stuff, my own problems, and this may be one of those too. Using the python3 app.py, I keep getting a failure as shown below. My deepest suspicion is that my lack of knowledge has got the better of me. Here's below the response I get .  I can't find any way to confront that ERROR and fix it. I've looked as well as I can on the internet, and because I can't find anything, I'm betting it's something I'm not doing. 
Any help to debug this problem of mine is appreciated. Settings.cfg is also pasted in.(And, btw, running Ubuntu instance at AWS EC2)
Thanks

$ python3 app.py
2022-12-03 22:27:28,675 - mtapi.mtapi - INFO - updating...
2022-12-03 22:27:29,219 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,220 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,223 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,224 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,239 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,240 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,241 - mtapi.mtapi - INFO - Stop R60 not found
2022-12-03 22:27:29,586 - mtapi.mtapi - ERROR - Couldn't connect to MTA server: Unexpected end-group tag.
2022-12-03 22:27:29,747 - mtapi._mtapithreader - INFO - Starting update thread...
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
2022-12-03 22:27:29,757 - werkzeug - INFO -  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)

Settings.cfg
MTA_KEY ='*********************'
STATIONS_FILE = './data/stations.json'
CROSS_ORIGIN =' '
MAX_TRAINS=10
MAX_MINUTES=30
CACHE_SECONDS=60
THREADED=True
DEBUG = True

**Comment by fixingthingsguy** [comment]
Hello Developers, I did some more investigation with some print statements, and here's what I see.
It looks like there is something wrong with my MTA KEY. I replaced and still getting the same error.
Don't know what I'm doing wrong, but I thought this might help you point out my error. Thanks
_______________________________________________________________________________________________
Added Debug print as follows in mtapi.py

Start excerpt
    def _load_mta_feed(self, feed_url):
        try:
            request = urllib.request.Request(feed_url)
            request.add_header('x-api-key', self._KEY)
            with contextlib.closing(urllib.request.urlopen(request)) as r:
                data = r.read()
                return FeedResponse(data)Start excerpt
    def _load_mta_feed(self, feed_url):
        try:
            request = urllib.request.Request(feed_url)
            request.add_header('x-api-key', self._KEY)
            with contextlib.closing(urllib.request.urlopen(request)) as r:
                data = r.read()
                return FeedResponse(data)

        except (urllib.error.URLError, google.protobuf.message.DecodeError, ConnectionResetError) as e:
            logger.error('Couldn\'t connect to MTA server: ' + str(e))
            print(feed_url)  #added
            print(data)         #added 
            print(self._KEY)   #added
            return False
End Excerpt
______________________________________________________________________________________________________________
Relevant Output
 Start excerpt
2022-12-06 02:36:28,964 - mtapi.mtapi - ERROR - Couldn't connect to MTA server: Unexpected end-group tag.
https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-7


        except (urllib.error.URLError, google.protobuf.message.DecodeError, ConnectionResetError) as e:
            logger.error('Couldn\'t connect to MTA server: ' + str(e))
            print(feed_url)  #added
            print(data)         #added 
            print(self._KEY)   #added
            return False
End Excerpt

Relevant Output:(annotated)

print(feed_url)
2022-12-06 02:36:28,964 - mtapi.mtapi - ERROR - Couldn't connect to MTA server: Unexpected end-group tag.
https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-7

print(data)
b'<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>nyct/gtfs-7</Key><RequestId>Z0H9PGTK3JMZ0JS7</RequestId><HostId>zhXgsqaSavY2dNKyWabvN2hKyo1kkF4mGVhO+Jvq6eYQHus0JXxfSSwCiWD9JrsFbSNV4wlmBbg=</HostId></Error>'

print(self._KEY) 
*************************************************************(blocked out)

**Comment by jonthornton** [comment]
I think you're seeing an issue that was recently fixed by https://github.com/jonthornton/MTAPI/commit/ced2c50f31941e56c922b709205f60cab449ac17. Try pulling the latest version and see if that fixes it.

**Comment by fixingthingsguy** [comment]
Thank you, that fixes it for me.
