### ISSUE TITLE
epoch timestamp in addition to 8601

### ISSUE THREAD

**Issue by ColdHeat** [jonthornton/MTAPI#37]
Hello! Thank you for this great project!

Would you be willing to accept a PR or add the functionality to also include a unix timestamp/epoch timestamp in addition to the datetime?

For example a current response: 

```
                {
                    "route": "N",
                    "time": "2023-02-26T22:07:06-05:00"
                },
```

What I propose:

```
                {
                    "route": "N",
                    "time": "2023-02-26T22:07:06-05:00"
                    "ts": 1677467226
                },
```

For my project it's much easier to work with an epoch timestamp than having to parse/load the datetime.

**Comment by jonthornton** [comment]
This seems like a tradeoff between making the data easier to parse and payload size; I'm reluctant to add duplicative fields that increase the response payload size.

Most languages have standard libraries that should make it easy to parse ISO 8601 timestamps into whatever format you need with one or two lines of code. Which language/framework are you working with?

(Apologies for the slow response. Also, I loved your post on Taking over a Dead IoT Company! Thanks for the WTFT shoutout.)

**Comment by ColdHeat** [comment]
Thanks for reading!

At the moment I was working with CircuitPython (https://circuitpython.org/) which now that I dig into it I think does have a way to add in datetime support. I was also doing some Arduino work but I think I can use `strptime` there. 

If I can get datetime working in CircuitPython/MicroPython I'll go ahead and close this issue. Although I do kind of think epoch time is easier to work with.

**Comment by ColdHeat** [comment]
I was able to get this working! Thanks for taking the time to respond and again thanks for the great API!

**Comment by jonthornton** [comment]
That's great! Good luck with your project.
