### ISSUE TITLE
Add G Train Support

### ISSUE THREAD

**Issue by jlaurito** [jonthornton/MTAPI#9]
Hi - the MTA has added a G-Train feed: documented [here](http://datamine.mta.info/list-of-feeds).

please add 'http://datamine.mta.info/mta_esi.php?feed_id=31' [here](https://github.com/jonthornton/MTAPI/blob/23f9df5145782bdf6829006e47c32c16edfd91b0/mtapi/mtapi.py#L63)

More broadly: I know this project hasn't been touched in a while, but I love it! I've been working off of it for a little while as I prep for a talk at pygotham and would love to submit a PR or two, if you'd allow me.

**Comment by jonthornton** [comment]
Indeed, this project could use a little love (and some unit tests). It meets my needs and I'm conservative about adding new features. However a PR to add the G train would be very welcome!

**Comment by jlaurito** [comment]
ok: if you give me permissions I'll submit, thanks!

**Comment by jonthornton** [comment]
No need for permissions, just fork this repo https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by jonthornton** [comment]
This was closed by https://github.com/jonthornton/MTAPI/commit/90b2cec49055d52ddf526d6044a982b13673fb75
